name: Java CI
on: [push]
jobs:
  MavenBuild:
     runs-on: ubuntu-latest
     steps:
      - name: Code Checkout
        uses: actions/checkout@v3
    
      - name: Code build
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '11'
      - run: 
            C:\Program Files\apache-maven-3.9.1\bin clean install
            
      - name: Code Test
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '11'
      -  run:  
            mvn test
           
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectkey=github-action-pipeline-codequality
      
            

            
