name: Java CI
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:
  Mavenbuild:
    runs-on: ubuntu-latest
    steps: 
    - name: code checkout
      uses: actions/checkout@v3
    
    - name: Code Build
      uses: actions/setup-java@v3
      with:
          distribution: "temurin"
          java-version: '11'
    
    - run: |
            pwd && ls -ltr 
            mvn clean install 
            
    - name: Code Test
      uses: actions/setup-java@v3
      with:
          distribution: "temurin"
          java-version: '11'
    
    - run: |
            pwd && ls -ltr 
            mvn test
 
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: ${{ secrets.NEXUS_URL }}
        username: admin
        password: ${{ secrets.NEXUS_PASSWORD }}
        format: maven2
        repository: maven-snapshots
        coordinates: groupId=helloworld artifactId=helloworld version=1.0-SNAPSHOT
        assets: extension=war
        filename: ./target/helloworld-1.0-SNAPSHOT.war
        
       
    
